apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection-manager
  template:
    metadata:
      labels:
        app: collection-manager
    spec:
      containers:
        - image: mikethenut/collection-manager:latest
          name: collection-manager
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com/cwvhzugl
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: cwvhzugl
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cm-postgres
                  key: password
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: collection-manager
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: collection-manager
