global:
  scrape_interval: 5s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'price-updater-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.0.192.220:8080']
  - job_name: 'collection-manager-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.0.72.126:8081']
